// This file is autogenerated by VESC Tool

#ifndef APPCONF_SIKORSKI_H_
#define APPCONF_SIKORSKI_H_

// VESC ID
#define APPCONF_CONTROLLER_ID 27

// Timeout
#define APPCONF_TIMEOUT_MSEC 1000

// Timeout Brake Current
#define APPCONF_TIMEOUT_BRAKE_CURRENT 0

// Can Status Message Mode
#define APPCONF_SEND_CAN_STATUS 0

// Can Status Rate
#define APPCONF_SEND_CAN_STATUS_RATE_HZ 50

// CAN Baud Rate
#define APPCONF_CAN_BAUD_RATE 2

// Pairing Done
#define APPCONF_PAIRING_DONE 0

// Enable Permanent UART
#define APPCONF_PERMANENT_UART_ENABLED 1

// Use UAVCAN
#define APPCONF_UAVCAN_ENABLE 0

// UAVCAN ESC Index
#define APPCONF_UAVCAN_ESC_INDEX 0

// APP to Use
#define APPCONF_APP_TO_USE 8

// Control Type
#define APPCONF_PPM_CTRL_TYPE 0

// PID Max ERPM
#define APPCONF_PPM_PID_MAX_ERPM 15000

// Input Deadband
#define APPCONF_PPM_HYST 0.15

// Pulselength Start
#define APPCONF_PPM_PULSE_START 1

// Pulselength End
#define APPCONF_PPM_PULSE_END 2

// Pulselength Center
#define APPCONF_PPM_PULSE_CENTER 1.5

// Median Filter
#define APPCONF_PPM_MEDIAN_FILTER 1

// Safe Start
#define APPCONF_PPM_SAFE_START 1

// Throttle Expo
#define APPCONF_PPM_THROTTLE_EXP 0

// Throttle Expo Brake
#define APPCONF_PPM_THROTTLE_EXP_BRAKE 0

// Throttle Expo Mode
#define APPCONF_PPM_THROTTLE_EXP_MODE 2

// Positive Ramping Time
#define APPCONF_PPM_RAMP_TIME_POS 0.3

// Negative Ramping Time
#define APPCONF_PPM_RAMP_TIME_NEG 0.1

// Multiple VESCs Over CAN
#define APPCONF_PPM_MULTI_ESC 1

// Traction Control
#define APPCONF_PPM_TC 0

// TC Max ERPM Difference
#define APPCONF_PPM_TC_MAX_DIFF 3000

// Max ERPM for direction switch
#define APPCONF_PPM_MAX_ERPM_FOR_DIR 4000

// Control Type
#define APPCONF_ADC_CTRL_TYPE 0

// Input Deadband
#define APPCONF_ADC_HYST 0.15

// ADC1 Min Voltage
#define APPCONF_ADC_VOLTAGE_START 0.9

// ADC1 Max Voltage
#define APPCONF_ADC_VOLTAGE_END 3

// ADC1 Center Voltage
#define APPCONF_ADC_VOLTAGE_CENTER 2

// ADC2 Min Voltage
#define APPCONF_ADC_VOLTAGE2_START 0.9

// ADC2 Max Voltage
#define APPCONF_ADC_VOLTAGE2_END 3

// Use Filter
#define APPCONF_ADC_USE_FILTER 1

// Safe Start
#define APPCONF_ADC_SAFE_START 1

// Invert Cruise Control Button
#define APPCONF_ADC_CC_BUTTON_INVERTED 0

// Invert Reverse Button
#define APPCONF_ADC_REV_BUTTON_INVERTED 0

// Invert ADC1 Voltage
#define APPCONF_ADC_VOLTAGE_INVERTED 0

// Invert ADC2 Voltage
#define APPCONF_ADC_VOLTAGE2_INVERTED 0

// Throttle Expo
#define APPCONF_ADC_THROTTLE_EXP 0

// Throttle Expo Brake
#define APPCONF_ADC_THROTTLE_EXP_BRAKE 0

// Throttle Expo Mode
#define APPCONF_ADC_THROTTLE_EXP_MODE 2

// Positive Ramping Time
#define APPCONF_ADC_RAMP_TIME_POS 0.3

// Negative Ramping Time
#define APPCONF_ADC_RAMP_TIME_NEG 0.1

// Multiple VESCs Over CAN
#define APPCONF_ADC_MULTI_ESC 1

// Traction Control
#define APPCONF_ADC_TC 0

// TC Max ERPM Difference
#define APPCONF_ADC_TC_MAX_DIFF 3000

// Update Rate
#define APPCONF_ADC_UPDATE_RATE_HZ 500

// Baudrate
#define APPCONF_UART_BAUDRATE 115200

// Control Type
#define APPCONF_CHUK_CTRL_TYPE 1

// Input Deadband
#define APPCONF_CHUK_HYST 0.15

// Positive Ramping Time
#define APPCONF_CHUK_RAMP_TIME_POS 0.9

// Negative Ramping Time
#define APPCONF_CHUK_RAMP_TIME_NEG 0.3

// ERPM Per Second Cruise Control
#define APPCONF_STICK_ERPM_PER_S_IN_CC 3000

// Throttle Expo
#define APPCONF_CHUK_THROTTLE_EXP 0

// Throttle Expo Brake
#define APPCONF_CHUK_THROTTLE_EXP_BRAKE 0

// Throttle Expo Mode
#define APPCONF_CHUK_THROTTLE_EXP_MODE 2

// Multiple VESCs Over CAN
#define APPCONF_CHUK_MULTI_ESC 1

// Traction Control
#define APPCONF_CHUK_TC 0

// TC Max ERPM Difference
#define APPCONF_CHUK_TC_MAX_DIFF 3000

// Speed
#define APPCONF_NRF_SPEED 1

// TX Power
#define APPCONF_NRF_POWER 3

// CRC
#define APPCONF_NRF_CRC 1

// Retry Delay
#define APPCONF_NRF_RETR_DELAY 0

// Retries
#define APPCONF_NRF_RETRIES 3

// Radio Channel
#define APPCONF_NRF_CHANNEL 76

// Address 0
#define APPCONF_NRF_ADDR_B0 198

// Address 1
#define APPCONF_NRF_ADDR_B1 199

// Address 2
#define APPCONF_NRF_ADDR_B2 0

// Send ACK
#define APPCONF_NRF_SEND_CRC_ACK 1

// APPCONF_DXTRAS_H_
#endif

