name: C/C++ CI

on:
  push:
    branches:
     - master
     - v2.3-New-HW
  pull_request:
    branches:
     - master
     - v2.3-New-HW

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: build/BLDC_4_BT_VESC.bin
